format_strings = true
imports_indent = "Block"
imports_layout = "HorizontalVertical"
match_arm_blocks = false
match_block_trailing_comma = true
max_width = 79
merge_imports = true
newline_style = "Unix"
normalize_comments = false
remove_nested_parens = true
reorder_impl_items = true
struct_field_align_threshold = 24
tab_spaces = 4
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = false
