use crate::gag_types::{Gag, GagName, GagType, GagType::*, SimpleGag};

pub const PASS: Gag = Gag {
    name:     GagName::Pass,
    gag_type: GagType::Pass,
    is_org:   false,
    base_dmg: 0,
    cost:     0,
};

pub const SIMPLE_PASS: SimpleGag = SimpleGag {
    gag_type: GagType::Pass,
    dmg:      0,
};

pub static DEFAULT_GAGS: &[Gag] = &[
    PASS,
    Gag {
        name:     GagName::BananaPeel,
        gag_type: Trap,
        is_org:   false,
        base_dmg: 12,
        cost:     10,
    },
    Gag {
        name:     GagName::Bikehorn,
        gag_type: Sound,
        is_org:   false,
        base_dmg: 4,
        cost:     12,
    },
    Gag {
        name:     GagName::Flowerpot,
        gag_type: Drop,
        is_org:   false,
        base_dmg: 10,
        cost:     14,
    },
    Gag {
        name:     GagName::SquirtingFlower,
        gag_type: Squirt,
        is_org:   false,
        base_dmg: 4,
        cost:     15,
    },
    Gag {
        name:     GagName::Cupcake,
        gag_type: Throw,
        is_org:   false,
        base_dmg: 6,
        cost:     16,
    },
    Gag {
        name:     GagName::BananaPeel,
        gag_type: Trap,
        is_org:   true,
        base_dmg: 13,
        cost:     15,
    },
    Gag {
        name:     GagName::Bikehorn,
        gag_type: Sound,
        is_org:   true,
        base_dmg: 5,
        cost:     17,
    },
    Gag {
        name:     GagName::Flowerpot,
        gag_type: Drop,
        is_org:   true,
        base_dmg: 11,
        cost:     19,
    },
    Gag {
        name:     GagName::SquirtingFlower,
        gag_type: Squirt,
        is_org:   true,
        base_dmg: 5,
        cost:     20,
    },
    Gag {
        name:     GagName::Cupcake,
        gag_type: Throw,
        is_org:   true,
        base_dmg: 7,
        cost:     21,
    },
    Gag {
        name:     GagName::Rake,
        gag_type: Trap,
        is_org:   false,
        base_dmg: 20,
        cost:     100,
    },
    Gag {
        name:     GagName::Whistle,
        gag_type: Sound,
        is_org:   false,
        base_dmg: 7,
        cost:     110,
    },
    Gag {
        name:     GagName::Sandbag,
        gag_type: Drop,
        is_org:   false,
        base_dmg: 18,
        cost:     120,
    },
    Gag {
        name:     GagName::GlassOfWater,
        gag_type: Squirt,
        is_org:   false,
        base_dmg: 8,
        cost:     140,
    },
    Gag {
        name:     GagName::FruitPieSlice,
        gag_type: Throw,
        is_org:   false,
        base_dmg: 10,
        cost:     160,
    },
    Gag {
        name:     GagName::Rake,
        gag_type: Trap,
        is_org:   true,
        base_dmg: 22,
        cost:     150,
    },
    Gag {
        name:     GagName::Whistle,
        gag_type: Sound,
        is_org:   true,
        base_dmg: 8,
        cost:     160,
    },
    Gag {
        name:     GagName::Sandbag,
        gag_type: Drop,
        is_org:   true,
        base_dmg: 19,
        cost:     170,
    },
    Gag {
        name:     GagName::GlassOfWater,
        gag_type: Squirt,
        is_org:   true,
        base_dmg: 9,
        cost:     190,
    },
    Gag {
        name:     GagName::FruitPieSlice,
        gag_type: Throw,
        is_org:   true,
        base_dmg: 11,
        cost:     210,
    },
    Gag {
        name:     GagName::Marbles,
        gag_type: Trap,
        is_org:   false,
        base_dmg: 35,
        cost:     1_000,
    },
    Gag {
        name:     GagName::Bugle,
        gag_type: Sound,
        is_org:   false,
        base_dmg: 11,
        cost:     1_100,
    },
    Gag {
        name:     GagName::Anvil,
        gag_type: Drop,
        is_org:   false,
        base_dmg: 30,
        cost:     1_200,
    },
    Gag {
        name:     GagName::Squirtgun,
        gag_type: Squirt,
        is_org:   false,
        base_dmg: 12,
        cost:     1_400,
    },
    Gag {
        name:     GagName::CreamPieSlice,
        gag_type: Throw,
        is_org:   false,
        base_dmg: 17,
        cost:     1_600,
    },
    Gag {
        name:     GagName::Marbles,
        gag_type: Trap,
        is_org:   true,
        base_dmg: 38,
        cost:     1_500,
    },
    Gag {
        name:     GagName::Bugle,
        gag_type: Sound,
        is_org:   true,
        base_dmg: 12,
        cost:     1_600,
    },
    Gag {
        name:     GagName::Anvil,
        gag_type: Drop,
        is_org:   true,
        base_dmg: 33,
        cost:     1_700,
    },
    Gag {
        name:     GagName::Squirtgun,
        gag_type: Squirt,
        is_org:   true,
        base_dmg: 13,
        cost:     1_900,
    },
    Gag {
        name:     GagName::CreamPieSlice,
        gag_type: Throw,
        is_org:   true,
        base_dmg: 18,
        cost:     2_100,
    },
    Gag {
        name:     GagName::Aoogah,
        gag_type: Sound,
        is_org:   false,
        base_dmg: 16,
        cost:     4_000,
    },
    Gag {
        name:     GagName::Quicksand,
        gag_type: Trap,
        is_org:   false,
        base_dmg: 50,
        cost:     4_500,
    },
    Gag {
        name:     GagName::BigWeight,
        gag_type: Drop,
        is_org:   false,
        base_dmg: 45,
        cost:     6_000,
    },
    Gag {
        name:     GagName::SeltzerBottle,
        gag_type: Squirt,
        is_org:   false,
        base_dmg: 21,
        cost:     7_000,
    },
    Gag {
        name:     GagName::FruitPie,
        gag_type: Throw,
        is_org:   false,
        base_dmg: 27,
        cost:     8_000,
    },
    Gag {
        name:     GagName::Aoogah,
        gag_type: Sound,
        is_org:   true,
        base_dmg: 17,
        cost:     6_000,
    },
    Gag {
        name:     GagName::Quicksand,
        gag_type: Trap,
        is_org:   true,
        base_dmg: 55,
        cost:     6_500,
    },
    Gag {
        name:     GagName::BigWeight,
        gag_type: Drop,
        is_org:   true,
        base_dmg: 49,
        cost:     8_000,
    },
    Gag {
        name:     GagName::SeltzerBottle,
        gag_type: Squirt,
        is_org:   true,
        base_dmg: 23,
        cost:     9_000,
    },
    Gag {
        name:     GagName::FruitPie,
        gag_type: Throw,
        is_org:   true,
        base_dmg: 29,
        cost:     10_000,
    },
    Gag {
        name:     GagName::ElephantTrunk,
        gag_type: Sound,
        is_org:   false,
        base_dmg: 21,
        cost:     12_000,
    },
    Gag {
        name:     GagName::TrapDoor,
        gag_type: Trap,
        is_org:   false,
        base_dmg: 70,
        cost:     18_000,
    },
    Gag {
        name:     GagName::Safe,
        gag_type: Drop,
        is_org:   false,
        base_dmg: 60,
        cost:     32_000,
    },
    Gag {
        name:     GagName::FireHose,
        gag_type: Squirt,
        is_org:   false,
        base_dmg: 30,
        cost:     48_000,
    },
    Gag {
        name:     GagName::CreamPie,
        gag_type: Throw,
        is_org:   false,
        base_dmg: 40,
        cost:     50_000,
    },
    Gag {
        name:     GagName::ElephantTrunk,
        gag_type: Sound,
        is_org:   true,
        base_dmg: 23,
        cost:     16_000,
    },
    Gag {
        name:     GagName::TrapDoor,
        gag_type: Trap,
        is_org:   true,
        base_dmg: 77,
        cost:     24_000,
    },
    Gag {
        name:     GagName::Safe,
        gag_type: Drop,
        is_org:   true,
        base_dmg: 66,
        cost:     36_000,
    },
    Gag {
        name:     GagName::FireHose,
        gag_type: Squirt,
        is_org:   true,
        base_dmg: 33,
        cost:     56_000,
    },
    Gag {
        name:     GagName::CreamPie,
        gag_type: Throw,
        is_org:   true,
        base_dmg: 44,
        cost:     60_000,
    },
    Gag {
        name:     GagName::StormCloud,
        gag_type: Squirt,
        is_org:   false,
        base_dmg: 80,
        cost:     400_000,
    },
    Gag {
        name:     GagName::Cake,
        gag_type: Throw,
        is_org:   false,
        base_dmg: 100,
        cost:     600_000,
    },
    Gag {
        name:     GagName::GrandPiano,
        gag_type: Drop,
        is_org:   false,
        base_dmg: 170,
        cost:     740_000,
    },
    Gag {
        name:     GagName::Tnt,
        gag_type: Trap,
        is_org:   false,
        base_dmg: 180,
        cost:     766_000,
    },
    Gag {
        name:     GagName::Foghorn,
        gag_type: Sound,
        is_org:   false,
        base_dmg: 50,
        cost:     820_000,
    },
    Gag {
        name:     GagName::StormCloud,
        gag_type: Squirt,
        is_org:   true,
        base_dmg: 88,
        cost:     470_000,
    },
    Gag {
        name:     GagName::Cake,
        gag_type: Throw,
        is_org:   true,
        base_dmg: 110,
        cost:     700_000,
    },
    Gag {
        name:     GagName::GrandPiano,
        gag_type: Drop,
        is_org:   true,
        base_dmg: 187,
        cost:     780_000,
    },
    Gag {
        name:     GagName::Tnt,
        gag_type: Trap,
        is_org:   true,
        base_dmg: 198,
        cost:     790_000,
    },
    Gag {
        name:     GagName::Foghorn,
        gag_type: Sound,
        is_org:   true,
        base_dmg: 55,
        cost:     920_000,
    },
    Gag {
        name:     GagName::Geyser,
        gag_type: Squirt,
        is_org:   false,
        base_dmg: 105,
        cost:     4_000_000,
    },
    Gag {
        name:     GagName::OperaSinger,
        gag_type: Sound,
        is_org:   false,
        base_dmg: 90,
        cost:     6_000_000,
    },
    Gag {
        name:     GagName::WeddingCake,
        gag_type: Throw,
        is_org:   false,
        base_dmg: 120,
        cost:     6_010_000,
    },
    Gag {
        name:     GagName::Toontanic,
        gag_type: Drop,
        is_org:   false,
        base_dmg: 180,
        cost:     7_000_000,
    },
    Gag {
        name:     GagName::Railroad,
        gag_type: Trap,
        is_org:   false,
        base_dmg: 195,
        cost:     7_010_000,
    },
    Gag {
        name:     GagName::Geyser,
        gag_type: Squirt,
        is_org:   true,
        base_dmg: 115,
        cost:     4_500_000,
    },
    Gag {
        name:     GagName::OperaSinger,
        gag_type: Sound,
        is_org:   true,
        base_dmg: 99,
        cost:     6_500_000,
    },
    Gag {
        name:     GagName::WeddingCake,
        gag_type: Throw,
        is_org:   true,
        base_dmg: 132,
        cost:     6_510_000,
    },
    Gag {
        name:     GagName::Toontanic,
        gag_type: Drop,
        is_org:   true,
        base_dmg: 198,
        cost:     7_010_000,
    },
    Gag {
        name:     GagName::Railroad,
        gag_type: Trap,
        is_org:   true,
        base_dmg: 214,
        cost:     7_777_777,
    },
];

pub fn hash_gag(gag: &Gag) -> u32 {
    u32::from(gag.name as u8) + if gag.is_org { 35 } else { 0 }
}

pub fn hash_picks(picks: &[Gag]) -> u32 {
    let mut hash = 0;
    for g in picks {
        hash <<= 8;
        hash |= hash_gag(g);
    }

    hash
}
